# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LuckyWheel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DZNEmptyDataSet'
#  pod 'Floaty'
  pod 'Masonry'
  pod 'SDCycleScrollView'
  # Pods for LuckyWheel
pod 'Masonry'
  target 'LuckyWheelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LuckyWheelUITests' do
    # Pods for testing
  end

end
