# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LuckyLottery' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LuckyLottery
pod 'Masonry'
  target 'LuckyLotteryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LuckyLotteryUITests' do
    # Pods for testing
  end

end
